name: Pull Request Analysis
on:
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  repo:
    name: Build and analyse PR from repo
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.head.repo.fork }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Build and analyse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn -B verify spotbugs:spotbugs org.sonarsource.scanner.maven:sonar-maven-plugin:sonar 
          -Dsonar.projectKey=ancouli_spring-test 
          -Dsonar.java.spotbugs.reportPaths=target/spotbugsXml.xml
          
  fork:
    name: Build and test PR from fork
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.fork }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Build and test
        run: mvn -B verify spotbugs:spotbugs
        
      - name: Save PR details
        run: echo "${{ github.event.number }},${{ github.head_ref || 'master'}},${{ github.base_ref }}" > pr_data.csv
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            src
            target
            pom.xml
            .git
            pr_data.csv
          retention-days: 1
          
      - name: Set output parameter
        run: echo "fork_output=fork_success" >> $GITHUB_OUTPUT