name: Pull Request Start
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Start 
        run: echo "Starting testing and analysis of pull request."